baseurl = "/"
languageCode = "en-us"
title = "Manabie Tech Blog"
theme = "hugo-theme-bootstrap4-blog"
enableRobotsTXT = true
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 3
copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
enableGitInfo = true
enableEmoji = true
disqusShortname = 'manabie'

#[imaging]
# Default resample filter used for resizing. Default is Box,
# # a simple and fast averaging filter appropriate for downscaling.
# # See https://github.com/disintegration/imaging
#resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
#quality = 82

[permalinks]
  posts = "/:year/:month/:slug/"
  page = "/:slug/"

[params]
  # Site author
  # author = ""

  # Description/subtitle for homepage (can be Markdown)
  description = "Sharing the humble technical knowledge we're using to improve education"

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # verification string for Google Webmaster Tools
  # google_verify_meta = "BAi69DROASu2b2mkVNA_EyUsobfH7Mq8BmSg2Rn-Zp4"

  # verification string for Bing Webmaster Tools
  # bing_verify_meta = "2CA373095D945D1AA256B1CD8A3DF872"

  # verification string for Yandex Webmaster Tools
  # yandex_verify_meta = "96b099438f75a04a"

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    # about = ""

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # twitter handle for the site (ideally not a person, eg: nytimes, flickr, etc)
    # twitter = ""

[[menu.sidebar]]
  name = "About Us"
  url = "https://manabie.com"

[[menu.sidebar]]
  name = "Careers"
  url = "https://manabie.breezy.hr"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
DefaultContentLanguage = "en"

[languages]
[languages.en]
  languageName = 'English'
  weight = 2

[languages.vi]
  languageName = 'Tiếng Việt'
  weight = 1